//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vingadores.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_heroi
    {
        public int id_heroi { get; set; }
        public string nm_heroi { get; set; }
        public string nm_nome { get; set; }
        public string ds_sexo { get; set; }
        public Nullable<int> vl_forca { get; set; }
        public Nullable<int> vl_poder { get; set; }
        public string ds_status { get; set; }
    }
}
